# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: hashing.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'hashing.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rhashing.proto\x12\x05proto\"\x9d\x01\n\x11WebSocketMetadata\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x02 \x01(\t\x12-\n\x0enode_meta_data\x18\x03 \x01(\x0b\x32\x13.proto.NodeMetaDataH\x00\x12\x33\n\x11request_meta_data\x18\x04 \x01(\x0b\x32\x16.proto.RequestMetaDataH\x00\x42\x06\n\x04\x64\x61ta\"E\n\x0cNodeMetaData\x12\x11\n\tnode_name\x18\x01 \x01(\t\x12\x0f\n\x07node_ip\x18\x02 \x01(\t\x12\x11\n\tnode_hash\x18\x03 \x01(\x05\"y\n\x0fRequestMetaData\x12\x1a\n\x12\x61ssigned_node_name\x18\x01 \x01(\t\x12\x18\n\x10\x61ssigned_node_ip\x18\x02 \x01(\t\x12\x14\n\x0crequest_hash\x18\x03 \x01(\x05\x12\x1a\n\x12\x61ssigned_node_hash\x18\x04 \x01(\x05\"?\n\x15WebSocketMetadataList\x12&\n\x04item\x18\x01 \x03(\x0b\x32\x18.proto.WebSocketMetadata\"\x07\n\x05\x45mpty2E\n\x04Node\x12=\n\x0fGetHashRingData\x12\x0c.proto.Empty\x1a\x1c.proto.WebSocketMetadataListB\x04Z\x02./b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hashing_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\002./'
  _globals['_WEBSOCKETMETADATA']._serialized_start=25
  _globals['_WEBSOCKETMETADATA']._serialized_end=182
  _globals['_NODEMETADATA']._serialized_start=184
  _globals['_NODEMETADATA']._serialized_end=253
  _globals['_REQUESTMETADATA']._serialized_start=255
  _globals['_REQUESTMETADATA']._serialized_end=376
  _globals['_WEBSOCKETMETADATALIST']._serialized_start=378
  _globals['_WEBSOCKETMETADATALIST']._serialized_end=441
  _globals['_EMPTY']._serialized_start=443
  _globals['_EMPTY']._serialized_end=450
  _globals['_NODE']._serialized_start=452
  _globals['_NODE']._serialized_end=521
# @@protoc_insertion_point(module_scope)
