/**
 * @fileoverview gRPC-Web generated client stub for proto
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.29.3
// source: hashing.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as hashing_pb from './hashing_pb'; // proto import: "hashing.proto"


export class NodeClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorGetHashRingData = new grpcWeb.MethodDescriptor(
    '/proto.Node/GetHashRingData',
    grpcWeb.MethodType.UNARY,
    hashing_pb.Empty,
    hashing_pb.WebSocketMetadataList,
    (request: hashing_pb.Empty) => {
      return request.serializeBinary();
    },
    hashing_pb.WebSocketMetadataList.deserializeBinary
  );

  getHashRingData(
    request: hashing_pb.Empty,
    metadata?: grpcWeb.Metadata | null): Promise<hashing_pb.WebSocketMetadataList>;

  getHashRingData(
    request: hashing_pb.Empty,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: hashing_pb.WebSocketMetadataList) => void): grpcWeb.ClientReadableStream<hashing_pb.WebSocketMetadataList>;

  getHashRingData(
    request: hashing_pb.Empty,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: hashing_pb.WebSocketMetadataList) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/proto.Node/GetHashRingData',
        request,
        metadata || {},
        this.methodDescriptorGetHashRingData,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/proto.Node/GetHashRingData',
    request,
    metadata || {},
    this.methodDescriptorGetHashRingData);
  }

}

