apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app-server
  namespace: demo
  labels:
    app: go-app
spec:
  selector:
    matchLabels:
      app: go-app
  replicas: 0
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
        - name: go-app
          image: nainani344sumit/goserver-for-consistencyhashing:v5
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 4000m
            requests:
              cpu: 2000m
            