apiVersion: v1
kind: Service
metadata:
  name: go-service
  namespace: demo
  labels:
    app: go-app
spec:
  type: ClusterIP
  selector:
    app: go-app
  ports:
    - protocol: TCP
      name: web
      port: 80
      targetPort: 8080